title: "Hello, world! I'm Veronica Santander"
description: >
  I am an English teacher who wants to help with fun and interesting English material.
  This description will appear in search results and your feed.xml.
baseurl: "/english-material" # Update with your subpath
url: "https://veronica202319.github.io" # Add your site's base URL

author: "Veronica Santander"
author-img: "assets/images/author.jpg"
about-author: "I am an English teacher who wants to share some interesting material for English classes."
social-github: "VeronicaSantander"
social-email: "vero9santander@gmail.com"

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page:num"
